# Decap CMS Configuration for MiAmor

backend:
  name: github
  repo: salamijoshua/MiAmor # IMPORTANT: Use your username/repo
  branch: main # The branch to update

# This is where the media files (like images) will be stored.
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# This defines the "collections" of content that can be edited.
collections:
  - name: "settings" # Internal name of the collection
    label: "Payment Settings" # What the client will see in the CMS sidebar
    files: # We are editing a single file, not a folder of files
      - label: "Account & Contact Details"
        name: "details"
        file: "_data/settings.yml" # The path to our data file
        fields: # The form fields the client will fill out
          - { label: "Account Holder Name", name: "account_name", widget: "string" }
          - { label: "Bank Name", name: "bank_name", widget: "string" }
          - { label: "Account Number", name: "account_number", widget: "string" }
          - { label: "WhatsApp Number (with country code, no +)", name: "whatsapp_number", widget: "string", hint: "Example: 2348012345678" }
